### ISSUE TITLE
Include cross-env in package.json?

### ISSUE THREAD

**Issue by brltdxd** [mattwaler/tea-stack#1]
Hi Matt,

I've tried your template today and came across an issue with `npm run build`.
I am on windows and using node inside Laragon when I got this error:
`NODE_ENV is not recognized as an internal or external command`.

What solved the issue for me was installing `cross-env` and I have modified the build value to this:
`"build": "cross-env NODE_ENV=production npm-run-all clean -p build:*"`

My question now would be if `cross-env` should be added as a default dev dependency in your template.

**Comment by mattwaler** [comment]
Wow, good catch! I'm a moron and forgot to install that dependency when I transferred these `package.json` scripts over from another template. I will install and push tonight!

**Comment by mattwaler** [comment]
Done!

**Comment by ineptian** [comment]
Idk if this is intentional, but cross-env is not a default dependency anymore, though its still needed on windows.
