### ISSUE TITLE
images: how should I manage the images ?

### ISSUE THREAD

**Issue by pascalandy** [mattwaler/tea-stack#14]
I tried to create /src/assets/img/logo.svg

Then, I used:

```
          <div>
            <img src="/_assets/img/logo.svg" class="h-7 sm:h-8" />
          </div>
```
but it does not work.

It would be nice to have an example. 
Thanks!

**Comment by mattwaler** [comment]
Hello @pascalandy!

Thanks for trying out the TEA stack repo! I can help you with your image problem.

Place all of your static files inside the `public` folder. This will get copied as-is into your `dist` build folder as you develop! 

For example, if you created the path and file:
`public/images/test.jpg`

You would link to it in your html like this: 
`<img src="/images/test.jpg">`

**Comment by pascalandy** [comment]
That's it! Thank you very much :)
