### ISSUE TITLE
Are you welling to get suggestions and features ?

### ISSUE THREAD

**Issue by pascalandy** [mattwaler/tea-stack#19]
If so I have few core one in mind. 

Cheers!

**Comment by mattwaler** [comment]
Hey @pascalandy,

The short answer is... maybe? If you want to list a few of them out here on this issue I'm happy to take a look, or if you want to fork the repo and create a PR with some new features that works too.

I'm trying to keep this template as simple and pragmatic as possible so people can quickly tailor the template to what they need!

**Comment by pascalandy** [comment]
Sure:

- 🔍 Optimized SEO with a meta.njk file (with a meta.json data file)
- 🖼 Eleventy Lazy Images Plugin

For these two feat. I saw how it's done in this repo: https://github.com/halfmage/11tea

I can do a PR for `🔍 Optimized SEO`
For the `Lazy Images`, would you like to check it out ?

**Comment by mattwaler** [comment]
I'll gladly accept a PR for a `meta.njk` file!

The the lazy images, I feel like that should be up to the developer and there are plenty of good methods for lazy loading, including native image lazy loading with the `loading="lazy"` attribute. There are also plenty of amazing libraries out there on the client side like `lazysizes` that can be used as well.

I think it's best to leave things like that up to the developer, and not pre-install dependencies for people.
