### ISSUE TITLE
Changing the `font family` in <body> does nothing

### ISSUE THREAD

**Issue by trashdad** [mattwaler/tea-stack#20]
using 

>`<body hx-boost="true" class="font-serif">`

 does not get inherited and translated. The resulting text is sans-serif regardless of it is set to monospace or serif.

**Comment by mattwaler** [comment]
@trashdad,

Are you running the dev command when you're adding this class? This project is running Tailwind in JIT mode, so the classes don't get built until they've been added to a template and Tailwind recognizes that. If you could shoot me a repo link to where you're experiencing this problem I can better diagnose it!

**Comment by mattwaler** [comment]
I pulled latest master and tried doing what you did while the dev command was running, and it works as expected:

<img width="1440" alt="Screen Shot 2021-09-02 at 10 11 37 PM" src="https://user-images.githubusercontent.com/32300026/131940093-db088e24-e095-46d1-8325-3fbfd11940a6.png">

**Comment by trashdad** [comment]
matt,

I'm sorry for bothering you about this, it was due to my misunderstanding of the mechanics. I'm rather new to all this and I appreciate you humoring my ignorance. Very much appreciate your attention to detail and diagnosing my issue nonetheless!

**Comment by mattwaler** [comment]
No worries @trashdad!

Just an FYI, I offer personalized pair-programming sessions if you would ever be interested!
https://mattwaler.com/instruction
