### ISSUE TITLE
Unexpected token '.'

### ISSUE THREAD

**Issue by chris-tietgen** [mattwaler/tea-stack#23]
Hey, I am trying to use this project and when I run `npm i` the following error occurs.

![image](https://user-images.githubusercontent.com/23318158/159826033-017d4c72-42cd-49ef-96ae-b546a8cc8142.png)

I have node version 16.14.2 set as the active version in nvm and I have npm version 8.5.0 installed.

Does this project require a specific version of node/npm?

**Comment by mattwaler** [comment]
Hey @slacker-king,

Yes, this project has a required node version, and an `.nvmrc` file present in the root of the project. You should be able to just run `nvm use`, then `npm i` and install without issues, I just did so locally and did not see any issues!

**Comment by chris-tietgen** [comment]
Thanks, I made sure I had node 16.8.0 installed via nvm, then performed a use on it, then ran `nvm use` in the console and I get the following error. Mind you this was after first attempting to run `nvm use` without 16.8.0 installed.

![image](https://user-images.githubusercontent.com/23318158/160014983-3f6f1f4e-98d2-4518-bcd0-c3f9c8d3d37d.png)

Here's my nvm info...

![image](https://user-images.githubusercontent.com/23318158/160015254-d063e8cd-d13a-4a3e-a346-7ebce879a72f.png)

**Comment by chris-tietgen** [comment]
Update. Looks like .nvmrc is not supported by the Windows version of nvm. Once I installed node 16.8.0 I was able to simple run `npm i` to get it working.
