### ISSUE TITLE
Troubles with repo

### ISSUE THREAD

**Issue by chris-tietgen** [mattwaler/tea-stack#24]
fyi, I ran into the following issues trying to use this repo on Windows.

- The Windows version of nvm doesn't support the .nvmrc file. At least not without jumping through hoops and creating a PowerShell script.
- The variables named $variable_name in the package.json don't work in Windows. They have to be renamed %variable_name%

You might want to add this to the Getting Started section of your read me.

**Comment by mattwaler** [comment]
Hey @slacker-king,

I'd be happy to check out a PR that adds windows support if you would like to provide it, but I can't promise I will merge it in!

I think most people who are using these templates are using either unix based systems that work out of the box with nvm, or running WSL on windows to get linux for their web development work.
